name: d_artnet_4
description: An artnet packet builder
version: 0.1.2
author: Christian Krueger <christian@blizzardpro.com>
homepage: https://github.com/TheOnlyCaky/d_artnet

environment:
  sdk: '>=1.19.0 <3.0.0'


 